### ISSUE TITLE
Avogadro2's main window incomplete

### ISSUE THREAD

**Issue by sagitter** [OpenChemistry/avogadroapp#167] opened 2021-06-04 21:14 UTC
Hi all.

 - Avogadroapp version: 1.94.0 + system `molequeue` compiled from [molequeue-0.9.0](https://github.com/OpenChemistry/molequeue/releases/tag/0.9.0)
 - Avogadrolibs: 1.94.0 + bundled `molequeue`
 - Qt: 5.15.2

**Desktop version:**
 - OS: Fedora
 - Version 34
 - Compiler: GCC-11.1.1

**Describe the bug**
![Screenshot from 2021-06-04 23-01-23](https://user-images.githubusercontent.com/5006433/120862734-f4476880-c578-11eb-931c-9a28dab397c5.png)

**Additional question**
`avogadro2-libs-1.94.0` now provides `molequeue` in bundle; `molequeue` will be [separately developed](https://github.com/OpenChemistry/molequeue) or will be always followed inside avogadro2-libs?

**Comment by ghutchis** [comment] 2021-06-04 21:31
Set a background color, and you should be good. Unfortunately, previous versions seemed to set an alpha and its saved in the settings... I'll see if i can code something, but if you set a color, it should work (and remember).

**Comment by ghutchis** [comment] 2021-06-04 21:34
As far as Molequeue, it's separately developed. Part of 1.94 removes the dependency.

**Comment by sagitter** [comment] 2021-06-05 10:20
> Set a background color, and you should be good. Unfortunately, previous versions seemed to set an alpha and its saved in the settings... I'll see if i can code something, but if you set a color, it should work (and remember).

It's working. Looks like an issue related to Wayland, using `QT_QPA_PLATFORM=xcb` helps to render Avogadro2 working.

```
$ avogadro2
QSocketNotifier: Can only be used with threads started with QThread
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```

**Comment by drew-parsons** [comment] 2021-06-29 00:39
I'm getting this error now with a linux build of avogadro2 (1.9.4) on Debian.

Setting a background colour as you suggested works around the problem.

I don't think it's related to Wayland.  I've disabled Wayland on my system (since it doesn't support video apps, needed in covid times), so launching from Gnome in X11  (Xorg).


There must be a way of initializing (or stopping transparency from initializing) without this transparency.  Qt windows aren't normally transparent like this.  What changed in regards to window gui configuration between 1.9.3 and 1.9.4?

In principle the default background should be black, from [`QColor(0,0,0,1.0)`](https://github.com/OpenChemistry/avogadroapp/blob/b2b873bb723faa310c31721f82803964c0bf2739/avogadro/mainwindow.cpp#L331) in 
```
QColor color = settings.value("backgroundColor", QColor(0,0,0,1.0)).value<QColor>();
```

For reference, Qt docs are [here](https://doc.qt.io/qt-5/qcolor.html#QColor-2)

Looks like there's a possible inconsistency in the alpha value. The API says it should be an integer, default 255. But avogadro uses a float value 1.0.  I'm not sure if the QColour API changed, but it looks as if floating value 1.0 was intended to mean "100%" opacity, equivalent to `a=255`. Instead it's getting set as `a=1`, meaning "mostly transparent". Qt's meaning for alpha is explained [here](https://doc.qt.io/qt-5/qcolor.html#alpha-blended-drawing).  They do provide methods `int alpha()` and `qreal alphaF()`. Perhaps in the past Qt provided a `QColor(int,int,int,qreal)` instantiator, but removed it because of this kind of problematic casting to `QColor(int,int,int,int)` 

I recommend just letting Qt use its own default (`a=255`), and set avogadro's background to `QColor(0,0,0)` without the transparency value.

**Comment by drew-parsons** [comment] 2021-06-29 01:21
I suspect this might also fix #108, although it might be a rendering rather than a transparency problem.

**Comment by drew-parsons** [comment] 2021-07-06 11:47
There's a separate transparency issue with the selection tool. With version 1.9.4, when a box is drawn using the cursor to select some atoms, the box has some transparency so any windows underneath the avogadro app become visible.  Likewise the pale blue halo around selected atoms exposes the underlying windows.

This problem is less black & white than the background colour issue - the selection halo should be transparent within the app! But it shouldn't expose windows outside the app.

I haven't been able to identify what's controlling it. There's nothing immediately obvious like there was for the backgroundColor setting. The only  transparency control I can see in avogadrolibs/avogadro/qtplugins/selectiontools is [`mesh->setOpacity(180)`](https://github.com/OpenChemistry/avogadrolibs/blob/5c867a2478af0b8e535fffd3f82838cea2dc4b3e/avogadro/qtplugins/selectiontool/selectiontool.cpp#L220).  There's also[ `selectedSpheres->setOpacity(0.42)`](https://github.com/OpenChemistry/avogadrolibs/blob/5c867a2478af0b8e535fffd3f82838cea2dc4b3e/avogadro/qtplugins/ballandstick/ballandstick.cpp#L64) in qtplugins/ballandstick.

**Comment by mquevill** [comment] 2021-07-07 15:30
I was going to open an issue on my own, but then found your comment. This is definitely a separate issue from the transparency of the background color, since it does not depend on the background at all. I opened #173 to track this separate issue better.

**Comment by ghutchis** [comment] 2021-07-08 18:07
This should now be fixed by https://github.com/OpenChemistry/avogadrolibs/pull/656

**Closed by ghutchis** 2021-07-08 18:07 UTC
